Description: "(SO8029) CDK for GCR solution: Quantum Computing in HCLS"
Parameters:
  NotebookInstanceType:
    Type: String
    Default: ml.m5.4xlarge
    Description: Sagemaker notebook instance type
  GitHubRepo:
    Type: String
    Default: https://github.com/amliuyong/aws-gcr-qc-life-science-public.git
    Description: Public GitHub repository
Resources:
  amazonbraketC6E30921:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          - ""
          - - amazon-braket-gcrqc-
            - Ref: AWS::AccountId
            - "-"
            - Ref: AWS::Region
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: gcr-qc-life-science-cdk-stack/amazon-braket/Resource
  gcrqcnotebookrole3D345977:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonBraketFullAccess
    Metadata:
      aws:cdk:path: gcr-qc-life-science-cdk-stack/gcr-qc-notebook-role/Resource
  gcrqcnotebookroleDefaultPolicyF44D109B:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Effect: Allow
            Resource:
              - arn:aws:s3:::amazon-braket-*
              - arn:aws:s3:::braketnotebookcdk-*
          - Action:
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
              - logs:CreateLogGroup
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:logs:*:"
                  - Ref: AWS::AccountId
                  - :log-group:/aws/sagemaker/*
          - Action: braket:*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: gcrqcnotebookroleDefaultPolicyF44D109B
      Roles:
        - Ref: gcrqcnotebookrole3D345977
    Metadata:
      aws:cdk:path: gcr-qc-life-science-cdk-stack/gcr-qc-notebook-role/DefaultPolicy/Resource
  installbraketsdk:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties:
      OnStart:
        - Content: IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc3VkbyAtdSBlYzItdXNlciAtaSA8PEVPUwpUTVBESVI9JChta3RlbXAgLWQpCmNkICIkVE1QRElSIgoKYXdzIHMzIGNwIHMzOi8vYnJha2V0bm90ZWJvb2tjZGstbm90ZWJvb2tsY2NzM2J1Y2tldGIzMDg5YjUwLTF3MWVwenZnMWttMWsvbm90ZWJvb2svYnJha2V0LW5vdGVib29rLWxjYy56aXAgYnJha2V0LW5vdGVib29rLWxjYy56aXAKdW56aXAgYnJha2V0LW5vdGVib29rLWxjYy56aXAKLi9pbnN0YWxsLnNoCgpub2h1cCBybSAtZnIgIiRUTVBESVIiICYKRU9TCgpleGl0IDAK
    Metadata:
      aws:cdk:path: gcr-qc-life-science-cdk-stack/install-braket-sdk
  GCRQCLifeScience:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType:
        Ref: NotebookInstanceType
      RoleArn:
        Fn::GetAtt:
          - gcrqcnotebookrole3D345977
          - Arn
      DefaultCodeRepository:
        Ref: GitHubRepo
      LifecycleConfigName:
        Fn::GetAtt:
          - installbraketsdk
          - NotebookInstanceLifecycleConfigName
      RootAccess: Enabled
      VolumeSizeInGB: 120
    Metadata:
      aws:cdk:path: gcr-qc-life-science-cdk-stack/GCRQCLifeScience
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE22PzY7CMAyEn4V7cKlWYrU3BCcktFTdJ8i6LjJpY5QfVlWUd980XDnNp9HYY7fQtl+w2xz0n9/iYJqE4gjST9Bo1Gm0nXZ6pkBOncT64CKG1b7G8IiVevISHdLKJTJwYLFZrfuS/4B0jGioJl+UFesZUi9THanaycS41LpKWXl9o1kbcpCK+y2BfkXMuVygLdKFR8IFJyqFI9/Um0jOWVkZCO6+ebZ7+CxP3j3z1kUbeCboX/oP/Uh1LwEBAAA=
    Metadata:
      aws:cdk:path: gcr-qc-life-science-cdk-stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  notebookName:
    Description: Notebook name
    Value:
      Fn::GetAtt:
        - GCRQCLifeScience
        - NotebookInstanceName
  bucketName:
    Description: S3 bucket name
    Value:
      Ref: amazonbraketC6E30921
  notebookUrl:
    Description: Notebook URL
    Value:
      Fn::Join:
        - ""
        - - https://console.aws.amazon.com/sagemaker/home?region=
          - Ref: AWS::Region
          - "#/notebook-instances/openNotebook/"
          - Fn::GetAtt:
              - GCRQCLifeScience
              - NotebookInstanceName
          - ?view=classic
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

